name: elm
description: elm 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hex: ^0.2.0
  # save data setting  
  shared_preferences: ^2.0.18
  intl: ^0.20.1
  # flutter_share: ^2.0.0 ** This plugin was discontinued after the flutter official one add support to files ** #
  share_plus: ^11.0.0
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.14.2 # change icons
  change_app_package_name: ^1.1.0 # remove later
  #flutter_bloc: ^8.1.6
  flutter_bloc: ^9.0.0
  # ui 
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  #uses-material-design: true

flutter:
  
  uses-material-design: true

  assets:
   #- assets/images/onboarding_one.PNG
   - assets/images/91k.jpg
   - assets/images/athkari5.jpg
   #- assets/sounds/click-1.mp3

  fonts:
     - family: Amiri
       fonts:
         - asset: assets/fonts/Amiri/Amiri-Regular.ttf
         - asset: assets/fonts/Amiri/Amiri-Bold.ttf
           weight: 700

     - family: Cairo
       fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
